'use client';
import {useState} from 'react';
import {AlertTriangle,ArrowRight,Box,Check,CheckCircle2,ChevronRight,CircleDot,Clock3,Download,ExternalLink,FileCheck2,FileSpreadsheet,FileText,Globe2,History,LayoutDashboard,Link2,Mail,Menu,Package,Pencil,QrCode,RotateCcw,ScanLine,Search,Send,Settings,ShieldCheck,Sparkles,UploadCloud,Users,X,XCircle} from 'lucide-react';
import {extractDocuments,generateSupplierRequest,publishPassport,simulateSupplierResponse,verifyField} from '@/lib/mock-services';
type View='overview'|'products'|'product'|'documents'|'extraction'|'review'|'gaps'|'request'|'record'|'passport'|'success'|'suppliers';
type Tone='verified'|'proposed'|'missing'|'expired'|'contradictory';
type Field={id:string;label:string;value:string;status:Tone;doc?:string;loc?:string;confidence?:number;excerpt?:string};
const seed:Field[]=[
 {id:'name',label:'Product name',value:'AeroStep Runner',status:'verified',doc:'BOM_S042.xlsx',loc:'Sheet 1 / B2'},
 {id:'sku',label:'SKU',value:'S-042',status:'verified',doc:'BOM_S042.xlsx',loc:'Sheet 1 / B3'},
 {id:'upper',label:'Upper material',value:'Full-grain bovine leather',status:'proposed',doc:'Supplier_L18.pdf',loc:'Page 3',confidence:92,excerpt:'The upper contains approximately 78% full-grain bovine leather supplied by LeatherWorks Italia.'},
 {id:'composition',label:'Upper composition',value:'78%',status:'proposed',doc:'Supplier_L18.pdf',loc:'Page 3',confidence:96,excerpt:'The upper contains approximately 78% full-grain bovine leather supplied by LeatherWorks Italia.'},
 {id:'origin',label:'Leather origin',value:'No value',status:'missing'},
 {id:'reach',label:'REACH declaration',value:'L18-REACH-2025',status:'expired',doc:'REACH_L18.pdf',loc:'Page 1'},
 {id:'sole',label:'Sole material',value:'Natural rubber / TPU',status:'contradictory',doc:'2 sources disagree',loc:'BOM + Supplier declaration'}];
const nav=[['overview','Overview',LayoutDashboard],['products','Products',Package],['documents','Documents',FileText],['suppliers','Suppliers',Users],['review','Reviews',FileCheck2],['passport','Passports',ScanLine]] as const;
const flow=[['documents','Documents'],['extraction','AI extraction'],['review','Review'],['gaps','Evidence gaps'],['request','Supplier request'],['passport','DPP']] as const;

export default function Home(){
 const[entered,setEntered]=useState(false),[view,setView]=useState<View>('product'),[fields,setFields]=useState(seed),[busy,setBusy]=useState(''),[toast,setToast]=useState(''),[drawer,setDrawer]=useState<Field|null>(null),[uploaded,setUploaded]=useState(false),[sent,setSent]=useState(false),[published,setPublished]=useState(false),[modal,setModal]=useState(false);
 const ready=fields.every(f=>f.status==='verified');
 const go=(v:View)=>{setView(v);scrollTo({top:0,behavior:'smooth'})},note=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2400)};
 const run=async()=>{setBusy('extract');await extractDocuments();setBusy('');go('extraction');note('7 fields extracted and linked to evidence.')};
 const accept=async(id:string)=>{setBusy(id);await verifyField(id);setFields(a=>a.map(f=>f.id===id?{...f,status:'verified'}:f));setBusy('');note('Field verified successfully.')};
 const resolve=()=>{setFields(a=>a.map(f=>f.id==='sole'?{...f,value:'Natural rubber',status:'verified',doc:'BOM_S042.xlsx',loc:'Sheet 1 / F8'}:f));note('Conflict resolved by Marco Rossi.')};
 const prepare=async()=>{setBusy('prepare');await generateSupplierRequest();setBusy('');go('request')};
 const send=async()=>{setBusy('send');await new Promise(r=>setTimeout(r,800));setSent(true);setBusy('');note('Supplier request sent.')};
 const response=async()=>{setBusy('response');await simulateSupplierResponse();setFields(a=>a.map(f=>f.id==='origin'?{...f,value:'Italy',status:'verified',doc:'LeatherOrigin_L18.pdf',loc:'Page 1',excerpt:'Country of origin: Italy'}:f.id==='reach'?{...f,value:'L18-REACH-2026',status:'verified',doc:'REACH_L18_2026.pdf',loc:'Page 1',excerpt:'Valid through 31 December 2026'}:f));setBusy('');go('record');note('New evidence processed. All required fields verified.')};
 const publish=async()=>{setBusy('publish');await publishPassport();setPublished(true);setModal(false);setBusy('');go('success')};
 if(!entered)return <Landing enter={()=>setEntered(true)}/>;
 return <main className="app-shell"><Side view={view} go={go}/><section className="workspace"><Top view={view}/><div className="content">
 {view==='overview'&&<Overview go={go}/>} {view==='products'&&<Products go={go} ready={ready}/>} {view==='suppliers'&&<Suppliers/>}
 {view==='product'&&<Product go={go} fields={fields} ready={ready}/>} {view==='documents'&&<Documents uploaded={uploaded} upload={()=>setUploaded(true)} run={run} busy={busy}/>} {view==='extraction'&&<Extraction fields={fields} open={setDrawer} go={go}/>} {view==='review'&&<Review fields={fields} open={setDrawer} accept={accept} resolve={resolve} busy={busy} go={go}/>} {view==='gaps'&&<Gaps prepare={prepare} busy={busy}/>} {view==='request'&&<Request sent={sent} send={send} response={response} busy={busy}/>} {view==='record'&&<Record fields={fields} open={setDrawer} go={go}/>} {view==='passport'&&<Passport ready={ready} published={published} publish={()=>setModal(true)}/>} {view==='success'&&<Success go={go} restart={()=>{setFields(seed);setSent(false);setPublished(false);go('product')}}/>}
 </div></section>{drawer&&<Drawer field={drawer} close={()=>setDrawer(null)}/>} {modal&&<PublishModal cancel={()=>setModal(false)} confirm={publish} busy={busy}/>} {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}</main>
}
function Landing({enter}:{enter:()=>void}){return <main className="entry-shell"><div className="entry-nav"><Brand/><span className="demo-pill"><CircleDot size={12}/> AeroStep S-042 demo</span></div><section className="entry-card"><div className="eyebrow"><Sparkles size={14}/> Evidence intelligence for product teams</div><h1>From product evidence<br/>to verified passport.</h1><p>TraceFlow turns supplier documents, certificates and product data into a structured, evidence-backed product record ready for compliance workflows and Digital Product Passports.</p><button className="primary large" onClick={enter}>Open demo workspace <ArrowRight size={17}/></button><div className="trust-line"><ShieldCheck size={16}/> AI proposes. Humans verify. Every fact has evidence.</div></section><div className="entry-orbit"/><div className="entry-orbit orbit-two"/></main>}
function Brand(){return <div className="brand"><span><Box size={17}/></span><strong>TraceFlow <em>AI</em></strong></div>}
function Side({view,go}:{view:View;go:(v:View)=>void}){return <aside className="sidebar"><Brand/><span className="workspace-label">Demo workspace</span><nav>{nav.map(([id,l,I])=><button key={id} onClick={()=>go(id)} className={view===id||(id==='products'&&['product','extraction','gaps','request','record'].includes(view))?'active':''}><I size={17}/><span>{l}</span></button>)}</nav><div className="sidebar-bottom"><button><Settings size={17}/><span>Settings</span></button><div className="profile"><span>MR</span><div><strong>Marco Rossi</strong><small>Compliance lead</small></div></div></div></aside>}
function Top({view}:{view:View}){return <header className="topbar"><div><button className="mobile-menu"><Menu size={17}/></button><span>Nova Footwear</span><ChevronRight size={14}/><strong>{({overview:'Overview',products:'Products',product:'AeroStep Runner',documents:'Documents',extraction:'AI extraction',review:'Reviews',gaps:'Evidence gaps',request:'Supplier request',record:'Verified record',passport:'Digital Product Passport',success:'Passport ready',suppliers:'Suppliers'} as Record<View,string>)[view]}</strong></div><div className="top-actions"><button className="icon-button"><Search size={17}/></button><span className="avatar">MR</span></div></header>}
function Head({over,title,sub,action}:{over?:string;title:string;sub:string;action?:React.ReactNode}){return <div className="page-head"><div>{over&&<span className="overline">{over}</span>}<h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Flow({active,complete=0}:{active:View;complete?:number}){return <div className="workflow">{flow.map(([id,l],i)=><button key={id} className={i<complete?'done':id===active?'current':''}><span>{i<complete?<Check size={13}/>:i+1}</span><small>{l}</small></button>)}</div>}
function PanelHead({title,sub}:{title:string;sub:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Principle(){return <section className="principle-card"><div className="principle-icon"><ShieldCheck size={20}/></div><h3>Evidence before publication</h3><p>Only human-verified information can enter the product passport.</p><div><Check size={14}/> Every fact remains traceable</div></section>}
function Product({go,fields,ready}:{go:(v:View)=>void;fields:Field[];ready:boolean}){const n=fields.filter(f=>f.status==='verified').length,r=ready?100:n>=5?71:43;return <><Head over="PRODUCT RECORD · S-042" title="AeroStep Runner" sub="Footwear  ·  Nova Footwear  ·  LeatherWorks Italia" action={<button className="primary" onClick={()=>go(ready?'record':'documents')}>{ready?'View verified record':'Start guided workflow'} <ArrowRight size={16}/></button>}/><section className="readiness-card"><div className="readiness-top"><div><span>Passport readiness</span><strong>{r}%</strong></div><div className={`status-note ${ready?'ok':''}`}><span/> {ready?'All required evidence verified':'3 actions required'}</div></div><div className="progress"><span style={{width:`${r}%`}}/></div><Flow active={ready?'passport':'review'} complete={ready?6:2}/></section><Stats fields={fields}/><div className="dashboard-grid"><section className="panel"><PanelHead title="Evidence record" sub="7 required product fields"/>{fields.slice(0,5).map(f=><FieldRow key={f.id} field={f} click={()=>go('extraction')}/>)}</section><aside className="side-stack"><Principle/><section className="panel compact"><PanelHead title="Recent activity" sub="Today"/><Activity color="green" title="AI extraction completed" sub="7 fields · 3 documents" time="10:22"/><Activity color="blue" title="Review is ready" sub="2 proposals awaiting you" time="10:24"/></section></aside></div></>}
function Stats({fields}:{fields:Field[]}){const c=(s:Tone)=>fields.filter(f=>f.status===s).length;return <div className="stats">{[['Verified',c('verified'),'green'],['Proposed',c('proposed'),'blue'],['Missing',c('missing'),'gray'],['Issues',c('expired')+c('contradictory'),'amber']].map(([l,v,t])=><div className="stat" key={String(l)}><span className={String(t)}/><div><strong>{v}</strong><small>{l}</small></div></div>)}</div>}
function FieldRow({field,click}:{field:Field;click:()=>void}){return <button className="field" onClick={click}><span className={`field-mark ${field.status}`}/><div className="field-main"><small>{field.label}</small><strong>{field.value}</strong><p>{field.doc?`${field.doc} · ${field.loc}`:'Required field'}</p></div><span className={`badge ${field.status}`}>{field.status}</span><ChevronRight size={16}/></button>}
function Documents({uploaded,upload,run,busy}:{uploaded:boolean;upload:()=>void;run:()=>void;busy:string}){const docs=[['BOM_S042.xlsx','Bill of Materials','v3 · 18 rows','Processed','sheet'],['Supplier_L18.pdf','Supplier declaration','v1.2 · 4 pages','Processed','pdf'],['REACH_L18.pdf','Certificate','2 pages','Expired','pdf']];return <><Head over="STEP 1 OF 6" title="Product documents" sub="Add source evidence for AeroStep Runner. Document lineage is preserved through every step." action={<button className="primary" onClick={run} disabled={!!busy}>{busy?<><Spinner/> Processing evidence</>:<>Run AI extraction <Sparkles size={16}/></>}</button>}/><section className="readiness-card slim"><Flow active="documents"/></section><div className="two-col"><section className="panel"><PanelHead title="Source documents" sub={`${3+(uploaded?1:0)} files attached`}/>{docs.map(d=><Doc key={d[0]} d={d}/>) }{uploaded&&<Doc d={['MaterialSpec_Aug.pdf','Technical sheet','1 page','Queued','pdf']}/>}</section><aside><label className="dropzone"><input type="file" onChange={upload}/><UploadCloud size={27}/><strong>Drop a document here</strong><span>or click to browse</span><small>PDF, XLSX, DOCX up to 25 MB</small></label>{uploaded&&<div className="inline-success"><CheckCircle2 size={16}/> Document added to processing queue.</div>}<Principle/></aside></div></>}
function Doc({d}:{d:string[]}){return <div className="doc-row"><span className={`doc-icon ${d[4]}`}>{d[4]==='sheet'?<FileSpreadsheet size={19}/>:<FileText size={19}/>}</span><div><strong>{d[0]}</strong><small>{d[1]} · {d[2]}</small></div><span className={`badge ${d[3].toLowerCase()}`}>{d[3]}</span><button>•••</button></div>}
function Extraction({fields,open,go}:{fields:Field[];open:(f:Field)=>void;go:(v:View)=>void}){return <><Head over="STEP 2 OF 6" title="Extraction results" sub="Structured facts are linked to source evidence. Nothing is published without review." action={<button className="primary" onClick={()=>go('review')}>Review proposals <ArrowRight size={16}/></button>}/><section className="readiness-card slim"><Flow active="extraction" complete={1}/></section><div className="extraction-layout"><section className="panel"><PanelHead title="Extracted product fields" sub="7 fields · 6 evidence links"/>{fields.map(f=><Evidence key={f.id} field={f} open={open}/>)}</section><aside className="analysis-card"><span><Sparkles size={15}/> Extraction complete</span><h3>TraceFlow found 3 items that need attention.</h3><ul><li><i className="blue"/>2 AI proposals</li><li><i/>1 missing field</li><li><i className="amber"/>2 evidence issues</li></ul><p>All source locations remain linked for validation.</p></aside></div></>}
function Evidence({field,open,actions}:{field:Field;open:(f:Field)=>void;actions?:React.ReactNode}){return <div className="evidence-field"><span className={`field-mark ${field.status}`}/><div className="field-main"><small>{field.label}</small><strong>{field.value}</strong><p>{field.doc&&<>{field.doc} · {field.loc}</>} {field.confidence&&<b>· {field.confidence}% confidence</b>}</p></div><span className={`badge ${field.status}`}>{field.status}</span>{actions||<button className="evidence-link" onClick={()=>open(field)} disabled={!field.doc}><Link2 size={14}/> Evidence</button>}</div>}
function Review({fields,open,accept,resolve,busy,go}:{fields:Field[];open:(f:Field)=>void;accept:(id:string)=>void;resolve:()=>void;busy:string;go:(v:View)=>void}){const proposals=fields.filter(f=>f.status==='proposed'),sole=fields.find(f=>f.id==='sole')!,done=!proposals.length&&sole.status==='verified';return <><Head over="STEP 3 OF 6" title="Review AI proposals" sub="AI suggestions are never automatically published." action={done?<button className="primary" onClick={()=>go('gaps')}>Inspect evidence gaps <ArrowRight size={16}/></button>:undefined}/><section className="readiness-card slim"><Flow active="review" complete={2}/></section><div className="review-stack">{['upper','composition'].map(id=>{const f=fields.find(x=>x.id===id)!;return <section className={`review-card ${f.status==='verified'?'reviewed':''}`} key={id}><div className="review-copy"><span className={`badge ${f.status}`}>{f.status}</span><small>{f.label}</small><h3>{f.value}</h3><button className="evidence-link" onClick={()=>open(f)}><Link2 size={14}/> {f.doc} · {f.loc}</button></div>{f.status==='proposed'?<div className="review-actions"><button className="quiet"><XCircle size={15}/> Reject</button><button className="quiet"><Pencil size={15}/> Edit</button><button className="accept" onClick={()=>accept(f.id)}>{busy===f.id?<Spinner/>:<Check size={15}/>} Accept</button></div>:<div className="review-meta"><CheckCircle2 size={18}/><span><strong>Verified by Marco Rossi</strong><small>Just now · Supplier_L18.pdf</small></span></div>}</section>})}<section className={`conflict-card ${sole.status==='verified'?'resolved':''}`}><div className="conflict-title"><AlertTriangle size={18}/><div><h3>{sole.status==='verified'?'Conflict resolved':'Conflicting evidence detected'}</h3><p>Sole material · two sources disagree</p></div></div>{sole.status==='contradictory'?<><div className="compare"><div><span>Evidence A</span><strong>Natural rubber</strong><small>BOM_S042.xlsx · Sheet 1 / F8</small></div><div><span>Evidence B</span><strong>TPU</strong><small>Supplier_L18.pdf · Page 4</small></div></div><div className="review-actions"><button className="accept" onClick={resolve}>Use Natural rubber</button><button className="quiet">Use TPU</button><button className="quiet"><Mail size={14}/> Request clarification</button></div></>:<div className="audit-note"><CheckCircle2 size={16}/> Natural rubber selected. Conflict resolved manually by Marco Rossi.</div>}</section></div></>}
function Gaps({prepare,busy}:{prepare:()=>void;busy:string}){return <><Head over="STEP 4 OF 6" title="Evidence gaps" sub="Missing, expired, and contradictory evidence is never silently ignored."/><section className="readiness-card slim"><Flow active="gaps" complete={3}/></section><div className="gap-layout"><section className="panel gap-list"><div className="gap-row"><span className="gap-icon"><Search size={18}/></span><div><span className="badge missing">Missing</span><h3>Leather origin</h3><p>No supporting evidence found.</p></div></div><div className="gap-row"><span className="gap-icon amber"><Clock3 size={18}/></span><div><span className="badge expired">Expired</span><h3>REACH declaration</h3><p>REACH_L18.pdf · Certificate expired.</p></div></div></section><aside className="blocker-card"><span className="overline">PUBLICATION CHECK</span><strong>2 blockers remaining</strong><p>Passport publication is unavailable until every required field is backed by valid evidence.</p><div><Users size={17}/><span><small>Recommended action</small><strong>Request updated evidence from LeatherWorks Italia</strong></span></div><button className="primary" onClick={prepare}>{busy?<Spinner/>:<Mail size={16}/>} Prepare supplier request</button></aside></div></>}
function Request({sent,send,response,busy}:{sent:boolean;send:()=>void;response:()=>void;busy:string}){return <><Head over="STEP 5 OF 6" title="Supplier request" sub="Generated directly from unresolved evidence requirements."/><section className="readiness-card slim"><Flow active="request" complete={4}/></section><div className="request-layout"><section className="panel composer"><div className="recipient"><span className="supplier-logo">LW</span><div><strong>LeatherWorks Italia</strong><small>L-18 · compliance@leatherworks.example</small></div><span className={`badge ${sent?'verified':'proposed'}`}>{sent?'Request sent':'Draft'}</span></div><label>Subject<input value="Missing compliance evidence — AeroStep S-042" readOnly/></label><label>Message<textarea rows={10} defaultValue={'Hello,\n\nTo complete the compliance record for AeroStep Runner (S-042), please provide the following information:\n\n1. Evidence confirming the leather country of origin.\n\n2. An updated and currently valid REACH declaration.\n\nThank you.\n\nTraceFlow automatically identified these requirements from the current product record.'}/></label><div className="composer-actions"><button className="quiet"><Pencil size={14}/> Edit request</button><button className="primary" onClick={send} disabled={sent}>{busy==='send'?<Spinner/>:<Send size={15}/>} {sent?'Request sent':'Send request'}</button></div></section><aside>{sent?<section className="panel request-status"><span className="eyebrow"><CheckCircle2 size={14}/> Request sent</span><h3>Supplier follow-up is active</h3><Timeline/><button className="primary demo-action" onClick={response}>{busy==='response'?<><Spinner/> Processing new evidence</>:<><Sparkles size={15}/> Simulate supplier response</>}</button></section>:<Principle/>}</aside></div></>}
function Timeline(){return <div className="timeline">{['Request generated','Request sent','Supplier opened request','Awaiting response'].map((x,i)=><div key={x} className="done"><span>{i<3?<Check size={11}/>:4}</span><p>{x}</p></div>)}</div>}
function Record({fields,open,go}:{fields:Field[];open:(f:Field)=>void;go:(v:View)=>void}){return <><div className="success-banner"><CheckCircle2 size={22}/><div><strong>All required evidence verified</strong><span>Passport readiness increased from 71% to 100%</span></div><b>100%</b></div><Head over="VERIFIED PRODUCT RECORD" title="AeroStep Runner" sub="S-042 · Nova Footwear · Last verified today at 10:32" action={<button className="primary" onClick={()=>go('passport')}>Generate passport <ArrowRight size={16}/></button>}/><div className="record-grid">{[['Identity',['name','sku']],['Materials',['upper','composition','origin','sole']],['Compliance',['reach']]].map(([s,ids])=><section className="panel record-section" key={String(s)}><PanelHead title={String(s)} sub="Verified information"/>{(ids as string[]).map(id=>{const f=fields.find(x=>x.id===id)!;return <div className="record-field" key={id}><div><small>{f.label}</small><strong>{f.value}</strong></div><button onClick={()=>open(f)}><Link2 size={14}/> Evidence</button></div>})}</section>)}<section className="panel history-section"><PanelHead title="Audit trail" sub="Immutable review history"/>{[['10:22','AI extracted Upper Material'],['10:24','Marco Rossi verified Upper Material'],['10:25','Marco Rossi resolved Sole Material contradiction'],['10:27','Supplier evidence requested'],['10:31','LeatherWorks Italia submitted new evidence'],['10:32','Leather origin and REACH verified'],['10:33','Product passport ready']].map(([t,e],i)=><div className="history-row" key={e}><time>{t}</time><span className={i===6?'green':''}/><p>{e}</p></div>)}</section></div></>}
function Passport({ready,published,publish}:{ready:boolean;published:boolean;publish:()=>void}){return <><Head over="STEP 6 OF 6" title="Digital Product Passport" sub="Preview the verified public record before publication." action={<button className="primary" disabled={!ready||published} onClick={publish}>{published?<><CheckCircle2 size={16}/> Passport live</>:<><Globe2 size={16}/> Publish passport</>}</button>}/><div className="passport-shell"><div className="passport-top"><Brand/><span className={`live-status ${published?'live':''}`}><span/>{published?'LIVE':'PRIVATE PREVIEW'}</span></div><div className="passport-hero"><div><span>Digital Product Passport</span><h2>AeroStep Runner</h2><p>S-042 · Footwear</p></div><div className="shoe-visual"><Package size={58}/><span>AS</span></div></div><div className="passport-content"><section><h3>Product identity</h3><PI l="Manufacturer" v="Nova Footwear"/><PI l="Product" v="AeroStep Runner"/><PI l="SKU" v="S-042"/></section><section><h3>Materials & origin</h3><PI l="Upper" v="Full-grain bovine leather"/><PI l="Composition" v="78%"/><PI l="Origin" v="Italy"/><PI l="Sole" v="Natural rubber"/></section><section><h3>Compliance</h3><PI l="REACH" v="Verified" ok/><PI l="Supplier" v="LeatherWorks Italia"/><PI l="Last verified" v="29 August 2026"/></section><aside className="qr-card"><div className="qr"><QrCode size={108}/></div><strong>Scan to access</strong><span>Digital Product Passport</span><button className="quiet">Preview public passport <ExternalLink size={14}/></button></aside></div><div className="passport-foot"><ShieldCheck size={15}/> Only verified information is shown in this passport.<span>TraceFlow verified</span></div></div>{!ready&&<div className="inline-warning"><AlertTriangle size={16}/> All required fields must be verified before publication.</div>}</>}
function PI({l,v,ok}:{l:string;v:string;ok?:boolean}){return <div className="passport-item"><span>{l}</span><strong>{v}{ok&&<CheckCircle2 size={14}/>}</strong></div>}
function Success({go,restart}:{go:(v:View)=>void;restart:()=>void}){return <section className="final-state"><div className="success-seal"><Check size={36}/></div><span className="eyebrow">PASSPORT READY</span><h1>AeroStep S-042 is passport ready</h1><p>Every required product fact is verified, traceable, and approved for publication.</p><div className="final-stats"><div><strong>100%</strong><span>required fields verified</span></div><div><strong>7</strong><span>verified fields</span></div><div><strong>0</strong><span>missing evidence</span></div><div><strong>0</strong><span>open issues</span></div></div><div className="final-actions"><button className="primary" onClick={()=>go('passport')}>View passport <ArrowRight size={16}/></button><button className="quiet" onClick={()=>go('record')}><History size={15}/> View evidence record</button><button className="quiet" onClick={restart}><RotateCcw size={15}/> Restart demo</button></div><div className="live-card"><span><span/> LIVE</span><strong>Passport published successfully</strong><small>DPP-S-042 · Published just now</small></div></section>}
function Overview({go}:{go:(v:View)=>void}){return <><Head title="Overview" sub="Product evidence health across Nova Footwear." action={<button className="primary" onClick={()=>go('product')}>Open AeroStep demo <ArrowRight size={16}/></button>}/><div className="metric-grid">{[['Products','24','+3 this month'],['Passport ready','16','67% of catalog'],['Needs review','5','9 open decisions'],['Blocked','3','Supplier evidence']].map(([l,v,s])=><div className="metric" key={l}><span>{l}</span><strong>{v}</strong><small>{s}</small></div>)}</div><div className="dashboard-grid"><section className="panel coverage"><PanelHead title="Evidence coverage" sub="Across active products"/><div className="coverage-chart"><div className="ring"><strong>87%</strong><span>covered</span></div><div><h3>Evidence quality is improving</h3><p>4.8% increase in verified fields this month.</p><span className="legend"><i/> Verified evidence</span><span className="legend muted"><i/> Attention required</span></div></div></section><section className="panel"><PanelHead title="Recent activity" sub="Latest workspace events"/><Activity color="green" title="AeroStep extraction completed" sub="7 product fields detected" time="10:22"/><Activity color="blue" title="Supplier request opened" sub="RubberTech Europe" time="09:48"/><Activity color="amber" title="Certificate expiring" sub="TerraWalk Boot" time="Yesterday"/></section></div></>}
function Products({go,ready}:{go:(v:View)=>void;ready:boolean}){const ps=[['AeroStep Runner','S-042',ready?'100%':'43%',ready?'Ready':'In progress'],['UrbanFlex Sneaker','U-105','78%','Needs review'],['TerraWalk Boot','T-210','54%','Missing evidence'],['MotionLite Runner','M-018','92%','Review']];return <><Head title="Products" sub="Evidence readiness across your product catalog."/><section className="panel product-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Readiness</span><span>Status</span><span/></div>{ps.map((p,i)=><button key={p[1]} onClick={()=>i===0&&go('product')}><span><span className="product-thumb"><Package size={16}/></span><strong>{p[0]}</strong></span><span>{p[1]}</span><span><i><b style={{width:p[2]}}/></i>{p[2]}</span><span className={`badge ${i===0&&ready?'verified':i===2?'missing':'proposed'}`}>{p[3]}</span><ChevronRight size={15}/></button>)}</section></>}
function Suppliers(){const ss=[['LeatherWorks Italia','L-18','8','92%','0'],['RubberTech Europe','R-09','11','81%','2'],['TextileNova','T-31','5','73%','1']];return <><Head title="Suppliers" sub="Evidence health and open requests across your network."/><div className="supplier-grid">{ss.map(s=><section className="supplier-card" key={s[1]}><div><span className="supplier-logo">{s[0].split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span><strong>{s[0]}</strong><small>Supplier ID {s[1]}</small></span></div><dl><div><dt>Products</dt><dd>{s[2]}</dd></div><div><dt>Evidence health</dt><dd>{s[3]}</dd></div><div><dt>Open requests</dt><dd>{s[4]}</dd></div></dl><button className="quiet">View supplier <ArrowRight size={14}/></button></section>)}</div></>}
function Activity({color,title,sub,time}:{color:string;title:string;sub:string;time:string}){return <div className="activity"><span className={color}/><div><strong>{title}</strong><small>{sub}</small></div><time>{time}</time></div>}
function Drawer({field,close}:{field:Field;close:()=>void}){return <><button className="drawer-backdrop" onClick={close}/><aside className="evidence-drawer"><header><div><span className="overline">SOURCE EVIDENCE</span><h2>{field.label}</h2></div><button onClick={close}><X size={18}/></button></header><div className="document-meta"><FileText size={19}/><div><strong>{field.doc}</strong><span>{field.loc}</span></div><button><Download size={15}/></button></div><div className="pdf-preview"><div className="paper"><span className="paper-brand">LEATHERWORKS ITALIA</span><h3>Supplier Material Declaration</h3><p>Product reference: AeroStep Runner S-042</p><p>This document confirms the material composition provided for the named product.</p><mark>{field.excerpt||`${field.label}: ${field.value}`}</mark><p>Signed by Compliance Office<br/>LeatherWorks Italia</p><small>{field.loc||'Page 1'} of 4</small></div></div><section className="extracted-box"><span>Extracted value</span><strong>{field.value}</strong>{field.confidence&&<div><span>Confidence</span><b>{field.confidence}%</b></div>}</section><div className="trace-note"><ShieldCheck size={16}/><p><strong>Evidence linked</strong><br/>This source remains attached through review and publication.</p></div></aside></>}
function PublishModal({cancel,confirm,busy}:{cancel:()=>void;confirm:()=>void;busy:string}){return <div className="modal-wrap"><button className="modal-backdrop" onClick={cancel}/><section className="modal"><div className="modal-icon"><Globe2 size={22}/></div><h2>Publish Digital Product Passport?</h2><p>Only verified fields will be published. The passport will become available through its public link and QR code.</p><div><button className="quiet" onClick={cancel}>Cancel</button><button className="primary" onClick={confirm}>{busy?<Spinner/>:<Globe2 size={15}/>} Publish passport</button></div></section></div>}
function Spinner(){return <span className="spinner"/>}
